created markdown and filled up
sta426hs2020/material pull request #43
Opened 2020-09-24 23:44 UTC by ymoon06

created content

2020-09-25 09:47 UTC, speckerf requested changes

2020-09-25 09:47 UTC, speckerf commented on week02-21sep2020/ChIPSeq.md
> +
```suggestion
(speckerf, Felix Specker)
```

2020-09-26 08:23 UTC, gjaq commented on week02-21sep2020/ChIPSeq.md
> +
```suggestion
(gjaq, Garance Jaques)
```

2020-09-26 09:36 UTC, KalvinDobler commented on week02-21sep2020/ChIPSeq.md
> +
```suggestion
In particular, this technique is used in oncogenomics for identifying the contribution of cancer-specific transcription factors in gene expression misregulation.
```

2020-09-26 09:36 UTC, KalvinDobler commented on week02-21sep2020/ChIPSeq.md
> +
```suggestion
I saw on the internet that people also use "peak-calling algorithms" : it allows to identify candidate peaks and testing candidate peaks for statistical significance.
Wikipedia: Peak calling is a computational method used to identify areas in a genome that have been enriched with aligned reads as a consequence of performing a ChIP-sequencing. These areas are those where a protein interacts with DNA. When the protein is a transcription factor, the enriched area is its transcription factor binding site.
```

2020-09-26 09:36 UTC, KalvinDobler commented on week02-21sep2020/ChIPSeq.md
> +
```suggestion
KalvinDobler, Kalvin Dobler
```

2020-09-26 09:36 UTC, KalvinDobler commented on week02-21sep2020/ChIPSeq.md
> +
```suggestion
[link_to_resource](https://www.illumina.com/techniques/sequencing/dna-sequencing/chip-seq.html)
```

2020-09-26 09:39 UTC, KalvinDobler commented on week02-21sep2020/ChIPSeq.md
> +KalvinDobler, Kalvin Dobler
```suggestion
(KalvinDobler, Kalvin Dobler)
```

2020-09-27 18:56 UTC, KalvinDobler commented on week02-21sep2020/ChIPSeq.md
> +[link_to_resource2](https://science.sciencemag.org/content/316/5830/1497?hwshib2=authn%3A1600986291%3A20200923%253Afa68459e-7542-4c13-93df-c33860c13fe5%3A0%3A0%3A0%3AmHdLlj0oHezGysPSsB%2FBGg%3D%3D)
```suggestion
[link_to_resource2](https://science.sciencemag.org/content/316/5830/1497?hwshib2=authn%3A1600986291%3A20200923%253Afa68459e-7542-4c13-93df-c33860c13fe5%3A0%3A0%3A0%3AmHdLlj0oHezGysPSsB%2FBGg%3D%3D)
[link_to_resource3](https://en.wikipedia.org/wiki/Peak_calling)
```

2020-09-28 11:06 UTC, closed without merging